name: Build game

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [ "win-x64", "win-arm64" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }
      - name: Publish AOT
        run: dotnet publish -c Release -r ${{ matrix.rid }} -p:PublishAot=true --self-contained true
      - uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.rid }}
          path: bin/Release/net8.0/${{ matrix.rid }}/native/*

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [ "linux-x64", "linux-arm64" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }

      - name: Publish AOT
        run: dotnet publish -c Release -r ${{ matrix.rid }} -p:PublishAot=true --self-contained true

      - uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.rid }}
          path: bin/Release/net8.0/${{ matrix.rid }}/native/*

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        rid: [ "osx-x64", "osx-arm64" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }

      - name: Publish AOT
        run: dotnet publish -c Release -r ${{ matrix.rid }} -p:PublishAot=true --self-contained true

      - uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.rid }}
          path: bin/Release/net8.0/${{ matrix.rid }}/native/*
